2025-04-19 15:22:23,617 INFO: 중고거래 플랫폼 시작 [in /var/www/html/secure-coding/app/__init__.py:96]
2025-04-19 15:22:45,212 ERROR: Exception on /chat/send/1 [POST] [in /var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/app/chat/routes.py", line 223, in send_message
    if request.is_xhr:
       ^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'is_xhr'
2025-04-19 15:22:51,367 ERROR: Exception on /chat/send/1 [POST] [in /var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/app/chat/routes.py", line 223, in send_message
    if request.is_xhr:
       ^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'is_xhr'
2025-04-19 15:22:52,874 ERROR: Exception on /chat/send/1 [POST] [in /var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/app/chat/routes.py", line 223, in send_message
    if request.is_xhr:
       ^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'is_xhr'
2025-04-19 15:22:54,802 ERROR: Exception on /chat/send/1 [POST] [in /var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/app/chat/routes.py", line 223, in send_message
    if request.is_xhr:
       ^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'is_xhr'
2025-04-19 15:22:55,520 ERROR: Exception on /chat/send/1 [POST] [in /var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/app/chat/routes.py", line 223, in send_message
    if request.is_xhr:
       ^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'is_xhr'
2025-04-19 15:22:55,678 ERROR: Exception on /chat/send/1 [POST] [in /var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/venv/lib/python3.12/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/secure-coding/app/chat/routes.py", line 223, in send_message
    if request.is_xhr:
       ^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'is_xhr'
